version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src/app:/app
    command: python app/main.py
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file: .env
volumes:
  postgres_data: