"""Add quiz_id to choice

Revision ID: 3174d185bc18
Revises: 79244e0d4277
Create Date: 2023-02-03 17:34:44.354540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3174d185bc18'
down_revision = '79244e0d4277'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choices', sa.Column('quiz_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'choices', 'quiz', ['quiz_id'], ['quiz_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'choices', type_='foreignkey')
    op.drop_column('choices', 'quiz_id')
    # ### end Alembic commands ###
